services:
  - type: web
    name: teste-usi-animal-api
    runtime: node
    plan: free
    buildCommand: cd back && npm install
    startCommand: cd back && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: FRONTEND_ORIGIN
        sync: false
      - key: DB_SERVER
        sync: false
      - key: DB_PORT
        value: 1433
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_ENCRYPT
        value: "true"
      - key: DB_TRUST_CERT
        value: "true"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: TOKEN_SECRET
        generateValue: true

  - type: web
    name: teste-usi-animal-front
    runtime: static
    plan: free
    buildCommand: cd front && npm install && npm run build
    staticPublishPath: front/dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        sync: false
